# Generated by Django 4.0.5 on 2022-06-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
